name: learn_alembic

services:
  db: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    entrypoint: ["/bin/bash", "./database_scripts/start_database_service.sh"]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: StrongPass!123
      DB_DATABASE: learn_alembic
    volumes:
      - ./local_data/mssql/data:/var/opt/mssql/data
      - ./database_scripts:/database_scripts
    ports:
      - 1433:1433
    networks:
      - learn_alembic
    healthcheck:
      test: ["CMD", "/bin/bash", "./database_scripts/check_health.sh"]
      interval: 5s
      timeout: 30s
      retries: 5

  alembic_app:
    env_file:
      - .env
    build:
      dockerfile: ./learn_alembic/Dockerfile
    volumes:
      - ./:/src:cache
    depends_on:
      db:
        condition: service_healthy
    networks:
      - learn_alembic

networks:
  learn_alembic:
